development:
  bucket: 'partreach_initial_bucket'
  access_key_id: ENV['AWS_ACCESS_KEY_ID']
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  max_file_size: 67108864
  acl: private

test:
  bucket: 'partreach_initial_bucket'
  access_key_id: ENV['AWS_ACCESS_KEY_ID']
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  max_file_size: 67108864
  acl: private

production:
  bucket: 'partreach_initial_bucket'
  access_key_id: ENV['AWS_ACCESS_KEY_ID']
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  max_file_size: 67108864
  acl: private