
development:
  adapter: postgresql
  encoding: unicode
  database: railsapp_development
  pool: 5
  username: railsapp
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: railsapp_test
  pool: 5
  username: railsapp
  password:
