class CrawlerSynapseWiki
  require 'mechanize'



  #goal of this method is to get the source file for every vendor page in the wiki
  def self.download_wiki_pages
    mech = CrawlerSynapseWiki.login

    Dir.mkdir('wikipages') unless File.exist?('wikipages')
    wiki_pages = CrawlerSynapseWiki.wiki_pages
    wiki_pages.each do |page_link|
      filename = page_link[1].gsub(/\W+/, "_")
      url = "https://wiki.synapse.com#{page_link[0]}"
      puts "#{filename} : #{url}"
      File.open("wikipages/#{filename}", "w:ASCII-8BIT") do |file|
        page = mech.get url
        file.write page.content
      end
    end

    # TODO log out (put in rescue block)
  end

  def self.login
    #heavily drawing upon http://docs.seattlerb.org/mechanize/EXAMPLES_rdoc.html
    mech = Mechanize.new
    mech.agent.http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    
    login_page = mech.get('https://sso.synapse.com/login')

    login_page.form_with(id: "login-form") do |f|
      f.username = "supply.better"
      f.password = "w!ndyNail22"
    end.click_button

    mech
  end



  #goal of this method is to take an individual source file and create the correct information in synapse's org
  #using a bunch of iteration and checking instead of regex, since that's not available via xpath in Rails
  def self.upload_wiki_pages

    #not doing
    # => noncompete (bret says no idea what for)

    #manually will do
    # => attachments
    # => prospective suppliers sheet

    #missing
    # => synapsers that used this one

    urls = [
"https://s3.amazonaws.com/supplybetter-synpgs/3D_Systems_Inc_formerly_Moeller_Design_",
"https://s3.amazonaws.com/supplybetter-synpgs/3M",
"https://s3.amazonaws.com/supplybetter-synpgs/ABC_Imaging",
"https://s3.amazonaws.com/supplybetter-synpgs/Abrisa_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/A_Brite_Plating",
"https://s3.amazonaws.com/supplybetter-synpgs/Absolute_Manufacturing",
"https://s3.amazonaws.com/supplybetter-synpgs/Accellent",
"https://s3.amazonaws.com/supplybetter-synpgs/Accuratus_Corporation",
"https://s3.amazonaws.com/supplybetter-synpgs/ACM_Holding",
"https://s3.amazonaws.com/supplybetter-synpgs/Acrylic_Concepts",
"https://s3.amazonaws.com/supplybetter-synpgs/Acteron_Corp",
"https://s3.amazonaws.com/supplybetter-synpgs/Acu_Line_Corporation",
"https://s3.amazonaws.com/supplybetter-synpgs/Adhesa_Plate",
"https://s3.amazonaws.com/supplybetter-synpgs/Advanced_Molding_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/Advanced_Prototype_Technologies_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Aetna_Plating",
"https://s3.amazonaws.com/supplybetter-synpgs/AIMMco",
"https://s3.amazonaws.com/supplybetter-synpgs/All_Flex_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Alliance_Packaging",
"https://s3.amazonaws.com/supplybetter-synpgs/Allied_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/Alljack",
"https://s3.amazonaws.com/supplybetter-synpgs/Allpak_Container",
"https://s3.amazonaws.com/supplybetter-synpgs/All_West_Components_amp_Fasteners_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Altaflex_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Alternative_Molding_Concepts",
"https://s3.amazonaws.com/supplybetter-synpgs/American_Precision_Protoyping_APP_",
"https://s3.amazonaws.com/supplybetter-synpgs/AmTouch_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Apex_Industries_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Apple_Rubber",
"https://s3.amazonaws.com/supplybetter-synpgs/Arcana_Precision_Machine",
"https://s3.amazonaws.com/supplybetter-synpgs/Argo_Spring_Manufacturing_Co_",
"https://s3.amazonaws.com/supplybetter-synpgs/Arlington_Plating_Company_Select_Connect_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/ARRK",
"https://s3.amazonaws.com/supplybetter-synpgs/Artcraft_Plating_amp_Finishing",
"https://s3.amazonaws.com/supplybetter-synpgs/Asahi_Group",
"https://s3.amazonaws.com/supplybetter-synpgs/ASH_Industries",
"https://s3.amazonaws.com/supplybetter-synpgs/ASKO_Processing_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Astro_Electroplating",
"https://s3.amazonaws.com/supplybetter-synpgs/Aurora_Technologies_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Automated_Metal_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/BAI_China_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Bayer_MaterialScience",
"https://s3.amazonaws.com/supplybetter-synpgs/Blue_Streak",
"https://s3.amazonaws.com/supplybetter-synpgs/Bob_s_Design_Engineering_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Buyken_Metal_Products",
"https://s3.amazonaws.com/supplybetter-synpgs/BYD_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Caliber_Precision",
"https://s3.amazonaws.com/supplybetter-synpgs/Capital_Industries_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Cardinal_Paint",
"https://s3.amazonaws.com/supplybetter-synpgs/Cascade_Container",
"https://s3.amazonaws.com/supplybetter-synpgs/Cascade_Engineering_Services_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Cascade_Engineering_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/Cascade_Precision_Incorporated",
"https://s3.amazonaws.com/supplybetter-synpgs/Cascade_Quality_Molding",
"https://s3.amazonaws.com/supplybetter-synpgs/Cashmere_Molding",
"https://s3.amazonaws.com/supplybetter-synpgs/Chicago_White_Metal_Casting",
"https://s3.amazonaws.com/supplybetter-synpgs/ChikaBird",
"https://s3.amazonaws.com/supplybetter-synpgs/Cirexx_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Ciscotec",
"https://s3.amazonaws.com/supplybetter-synpgs/Classic_Components",
"https://s3.amazonaws.com/supplybetter-synpgs/Cofan_USA",
"https://s3.amazonaws.com/supplybetter-synpgs/Cole_ScreenPrint_Inc",
"https://s3.amazonaws.com/supplybetter-synpgs/Component_Supply_Company",
"https://s3.amazonaws.com/supplybetter-synpgs/Component_Surfaces",
"https://s3.amazonaws.com/supplybetter-synpgs/Composite_Applications",
"https://s3.amazonaws.com/supplybetter-synpgs/Concept_Reality",
"https://s3.amazonaws.com/supplybetter-synpgs/Conrad_Manufacturing",
"https://s3.amazonaws.com/supplybetter-synpgs/Constance_Machine",
"https://s3.amazonaws.com/supplybetter-synpgs/Control_Plastics",
"https://s3.amazonaws.com/supplybetter-synpgs/CoorsTek",
"https://s3.amazonaws.com/supplybetter-synpgs/Corning_Glass",
"https://s3.amazonaws.com/supplybetter-synpgs/Coxon",
"https://s3.amazonaws.com/supplybetter-synpgs/Creganna_Tactx_Medical",
"https://s3.amazonaws.com/supplybetter-synpgs/Custom_Mold_amp_Design",
"https://s3.amazonaws.com/supplybetter-synpgs/Cybershield",
"https://s3.amazonaws.com/supplybetter-synpgs/CyberTouch_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/CymMetrick",
"https://s3.amazonaws.com/supplybetter-synpgs/Cymmetrik",
"https://s3.amazonaws.com/supplybetter-synpgs/Danco",
"https://s3.amazonaws.com/supplybetter-synpgs/Definitive_Solutions_amp_Technologies_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Designcraft_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/DOTT_Industries",
"https://s3.amazonaws.com/supplybetter-synpgs/Double_D_Mfg",
"https://s3.amazonaws.com/supplybetter-synpgs/Douglas_Corp",
"https://s3.amazonaws.com/supplybetter-synpgs/Douglas_Stamping",
"https://s3.amazonaws.com/supplybetter-synpgs/Duke_Empirical",
"https://s3.amazonaws.com/supplybetter-synpgs/Duray_Plating_Co_",
"https://s3.amazonaws.com/supplybetter-synpgs/DYMAX",
"https://s3.amazonaws.com/supplybetter-synpgs/Dynacast",
"https://s3.amazonaws.com/supplybetter-synpgs/Dynacept",
"https://s3.amazonaws.com/supplybetter-synpgs/E_Fab",
"https://s3.amazonaws.com/supplybetter-synpgs/Eika_Kasei_HK_Co_Ltd_",
"https://s3.amazonaws.com/supplybetter-synpgs/Ellsworth",
"https://s3.amazonaws.com/supplybetter-synpgs/Emerald_city_graphics",
"https://s3.amazonaws.com/supplybetter-synpgs/Engent_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Epner_Technology",
"https://s3.amazonaws.com/supplybetter-synpgs/EuroKera",
"https://s3.amazonaws.com/supplybetter-synpgs/Exotic_Tool_Welding",
"https://s3.amazonaws.com/supplybetter-synpgs/Express_Finishing",
"https://s3.amazonaws.com/supplybetter-synpgs/Farwest_Aircraft",
"https://s3.amazonaws.com/supplybetter-synpgs/Farwest_Fabrication",
"https://s3.amazonaws.com/supplybetter-synpgs/Faspro_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Fastenix",
"https://s3.amazonaws.com/supplybetter-synpgs/Fast_Signs",
"https://s3.amazonaws.com/supplybetter-synpgs/Fathom",
"https://s3.amazonaws.com/supplybetter-synpgs/Feedback_on_Coxon",
"https://s3.amazonaws.com/supplybetter-synpgs/Ferrera_Tooling_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Ferro_Ceramic_Grinding_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Finishing_Unlimited_Inc",
"https://s3.amazonaws.com/supplybetter-synpgs/First_Cut_ProtoLabs_",
"https://s3.amazonaws.com/supplybetter-synpgs/FJM_Security_Products",
"https://s3.amazonaws.com/supplybetter-synpgs/Flock_Tex",
"https://s3.amazonaws.com/supplybetter-synpgs/Fluke_Metal_Products",
"https://s3.amazonaws.com/supplybetter-synpgs/Foctek_Photonics_Inc",
"https://s3.amazonaws.com/supplybetter-synpgs/Form_Factor_Inc",
"https://s3.amazonaws.com/supplybetter-synpgs/Fotofab",
"https://s3.amazonaws.com/supplybetter-synpgs/Frank_Ward_Precision_Prototype",
"https://s3.amazonaws.com/supplybetter-synpgs/FULLRIVER_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Future_Power_Technologies_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Gardico_Incorporated",
"https://s3.amazonaws.com/supplybetter-synpgs/Gary_Hansen",
"https://s3.amazonaws.com/supplybetter-synpgs/General_Foundry_Service",
"https://s3.amazonaws.com/supplybetter-synpgs/General_Super_Plating",
"https://s3.amazonaws.com/supplybetter-synpgs/Genesis_Plastics_Welding",
"https://s3.amazonaws.com/supplybetter-synpgs/Gillaspie_Manufacturing",
"https://s3.amazonaws.com/supplybetter-synpgs/GKS_Services_Corp",
"https://s3.amazonaws.com/supplybetter-synpgs/Global_Lighting_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/GMBattery_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/GM_Nameplate",
"https://s3.amazonaws.com/supplybetter-synpgs/Goldstar_Mold_Shenzhen",
"https://s3.amazonaws.com/supplybetter-synpgs/GPI_Prototype_and_Manufacturing_Services",
"https://s3.amazonaws.com/supplybetter-synpgs/Gumstix_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Harting_MID",
"https://s3.amazonaws.com/supplybetter-synpgs/Henkel_Loctite",
"https://s3.amazonaws.com/supplybetter-synpgs/Herold_Precision_Metals",
"https://s3.amazonaws.com/supplybetter-synpgs/High_End_Finishes",
"https://s3.amazonaws.com/supplybetter-synpgs/High_Energy_Metals_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/HN_Lockwood",
"https://s3.amazonaws.com/supplybetter-synpgs/Ideas_Prototyped_LLC",
"https://s3.amazonaws.com/supplybetter-synpgs/image",
"https://s3.amazonaws.com/supplybetter-synpgs/INCS",
"https://s3.amazonaws.com/supplybetter-synpgs/Industrial_Plating_Corporation",
"https://s3.amazonaws.com/supplybetter-synpgs/Industrial_Service_Co_",
"https://s3.amazonaws.com/supplybetter-synpgs/Innovation_Fabrication",
"https://s3.amazonaws.com/supplybetter-synpgs/INTA_Technologies_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Introduction_of_the_Vendor_Information_for_Confluence_2_3_",
"https://s3.amazonaws.com/supplybetter-synpgs/Italix",
"https://s3.amazonaws.com/supplybetter-synpgs/Jemco",
"https://s3.amazonaws.com/supplybetter-synpgs/Jet_City_Laser",
"https://s3.amazonaws.com/supplybetter-synpgs/JetEdge",
"https://s3.amazonaws.com/supplybetter-synpgs/Jimani_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/JM_Victor",
"https://s3.amazonaws.com/supplybetter-synpgs/Kaso_Plastics",
"https://s3.amazonaws.com/supplybetter-synpgs/Kelly_Plating_Co_",
"https://s3.amazonaws.com/supplybetter-synpgs/Kemeera_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Kinetics",
"https://s3.amazonaws.com/supplybetter-synpgs/Kingstec",
"https://s3.amazonaws.com/supplybetter-synpgs/Koller_Craft_Plastic_Products",
"https://s3.amazonaws.com/supplybetter-synpgs/Lancaster_Metals_Science_Co_",
"https://s3.amazonaws.com/supplybetter-synpgs/Laser_Cutting_Northwest",
"https://s3.amazonaws.com/supplybetter-synpgs/Laser_Light_Technologies_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Laser_Reproductions",
"https://s3.amazonaws.com/supplybetter-synpgs/Leader_Plating",
"https://s3.amazonaws.com/supplybetter-synpgs/Leader_Tech",
"https://s3.amazonaws.com/supplybetter-synpgs/Lee_Spring",
"https://s3.amazonaws.com/supplybetter-synpgs/Leister",
"https://s3.amazonaws.com/supplybetter-synpgs/LensOne_Lens_Technology",
"https://s3.amazonaws.com/supplybetter-synpgs/Li_Polymer_Batteries_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/LiveWire_Prototyping",
"https://s3.amazonaws.com/supplybetter-synpgs/LPKF",
"https://s3.amazonaws.com/supplybetter-synpgs/Lubrizol_Advanced_Materials",
"https://s3.amazonaws.com/supplybetter-synpgs/Made_3D",
"https://s3.amazonaws.com/supplybetter-synpgs/Magic_Metals",
"https://s3.amazonaws.com/supplybetter-synpgs/Mary_s_learning_Wiki",
"https://s3.amazonaws.com/supplybetter-synpgs/Master_Spring_amp_Wire_Form",
"https://s3.amazonaws.com/supplybetter-synpgs/Material_Connexion",
"https://s3.amazonaws.com/supplybetter-synpgs/MC_Custom_Products",
"https://s3.amazonaws.com/supplybetter-synpgs/McKechnie_Vehicle_Components",
"https://s3.amazonaws.com/supplybetter-synpgs/McSweeney_Steel_Co_",
"https://s3.amazonaws.com/supplybetter-synpgs/Metal_Motion",
"https://s3.amazonaws.com/supplybetter-synpgs/MGS_Manufacturing_Group",
"https://s3.amazonaws.com/supplybetter-synpgs/Microform_Precision",
"https://s3.amazonaws.com/supplybetter-synpgs/Micro_Machine_Shop",
"https://s3.amazonaws.com/supplybetter-synpgs/Micron_3D_Printing",
"https://s3.amazonaws.com/supplybetter-synpgs/Midwest_Prototyping",
"https://s3.amazonaws.com/supplybetter-synpgs/Mikros_Engineering",
"https://s3.amazonaws.com/supplybetter-synpgs/Mitsubishi_Engineered_Plastics_MEP_",
"https://s3.amazonaws.com/supplybetter-synpgs/Mobius_Rapid_Prototyping",
"https://s3.amazonaws.com/supplybetter-synpgs/Model_Solution",
"https://s3.amazonaws.com/supplybetter-synpgs/Modelwerks",
"https://s3.amazonaws.com/supplybetter-synpgs/Modern_Engineering",
"https://s3.amazonaws.com/supplybetter-synpgs/Moeller_Design_amp_Development",
"https://s3.amazonaws.com/supplybetter-synpgs/Mold_Rite",
"https://s3.amazonaws.com/supplybetter-synpgs/Molex_Antenna_MID_Division",
"https://s3.amazonaws.com/supplybetter-synpgs/Motion_Mechanisms",
"https://s3.amazonaws.com/supplybetter-synpgs/MPC_Plating",
"https://s3.amazonaws.com/supplybetter-synpgs/National_Instruments",
"https://s3.amazonaws.com/supplybetter-synpgs/Nebula_Design",
"https://s3.amazonaws.com/supplybetter-synpgs/NIC",
"https://s3.amazonaws.com/supplybetter-synpgs/Nissha_USA",
"https://s3.amazonaws.com/supplybetter-synpgs/Northern_Engraving",
"https://s3.amazonaws.com/supplybetter-synpgs/Northwest_Etch_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/Oakdale_Precision",
"https://s3.amazonaws.com/supplybetter-synpgs/Odyssey_Plastics",
"https://s3.amazonaws.com/supplybetter-synpgs/OmniFab",
"https://s3.amazonaws.com/supplybetter-synpgs/Omnitech",
"https://s3.amazonaws.com/supplybetter-synpgs/O_Rings_West",
"https://s3.amazonaws.com/supplybetter-synpgs/PacTec",
"https://s3.amazonaws.com/supplybetter-synpgs/PacWest_Sales",
"https://s3.amazonaws.com/supplybetter-synpgs/Pad_Printing_Services_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Pathway_design",
"https://s3.amazonaws.com/supplybetter-synpgs/Pathway_Designs",
"https://s3.amazonaws.com/supplybetter-synpgs/Pearce_Design_LLC",
"https://s3.amazonaws.com/supplybetter-synpgs/Pegasus_Northwest",
"https://s3.amazonaws.com/supplybetter-synpgs/Pequot_Tool_and_Mfg_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Peridot_Corp_",
"https://s3.amazonaws.com/supplybetter-synpgs/Pinehurst",
"https://s3.amazonaws.com/supplybetter-synpgs/Pioneer_Metal_Finishing",
"https://s3.amazonaws.com/supplybetter-synpgs/Plastic_Assembly_Systems_PAS_",
"https://s3.amazonaws.com/supplybetter-synpgs/Plastic_Innovations",
"https://s3.amazonaws.com/supplybetter-synpgs/Plastic_Metal_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/Plastic_Platers_Inc",
"https://s3.amazonaws.com/supplybetter-synpgs/PolyOne",
"https://s3.amazonaws.com/supplybetter-synpgs/Potential_ME_Vendors_List",
"https://s3.amazonaws.com/supplybetter-synpgs/Pro_CNC_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Production_Plating",
"https://s3.amazonaws.com/supplybetter-synpgs/ProtoCafe",
"https://s3.amazonaws.com/supplybetter-synpgs/Protocam",
"https://s3.amazonaws.com/supplybetter-synpgs/Protolabs",
"https://s3.amazonaws.com/supplybetter-synpgs/Protomold",
"https://s3.amazonaws.com/supplybetter-synpgs/Proto_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/Prototek_Sheetmetal_Fabrication_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Proven_Process_Medical_Devices",
"https://s3.amazonaws.com/supplybetter-synpgs/Providence_Metallizing",
"https://s3.amazonaws.com/supplybetter-synpgs/PTA_Plastics",
"https://s3.amazonaws.com/supplybetter-synpgs/Pulse_Technologies_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Quaker_City_Plating",
"https://s3.amazonaws.com/supplybetter-synpgs/Qualitel_Corp_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Queen_City_Plating",
"https://s3.amazonaws.com/supplybetter-synpgs/Quickparts_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Rapid_Sheet_Metal_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Rayotek",
"https://s3.amazonaws.com/supplybetter-synpgs/R_D_Wing",
"https://s3.amazonaws.com/supplybetter-synpgs/Read_Me",
"https://s3.amazonaws.com/supplybetter-synpgs/Read_Me_for_Confluence_2_3_",
"https://s3.amazonaws.com/supplybetter-synpgs/Reell_Precision_Manufacturing",
"https://s3.amazonaws.com/supplybetter-synpgs/Reliance_Engineering",
"https://s3.amazonaws.com/supplybetter-synpgs/Reliance_Manufacturing_Corporation",
"https://s3.amazonaws.com/supplybetter-synpgs/RIM_Manufacturing",
"https://s3.amazonaws.com/supplybetter-synpgs/Rimstar",
"https://s3.amazonaws.com/supplybetter-synpgs/RK_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/RMC_Powder_Coating",
"https://s3.amazonaws.com/supplybetter-synpgs/RPDG_Rapid_Product_Development_Group_",
"https://s3.amazonaws.com/supplybetter-synpgs/RPDG_Rapid_Product_Development_Group_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/RTP_Plastics_Company",
"https://s3.amazonaws.com/supplybetter-synpgs/Ryerson",
"https://s3.amazonaws.com/supplybetter-synpgs/Sabic_Innovative_Plastics",
"https://s3.amazonaws.com/supplybetter-synpgs/Saint_Gobain_Performance_Plastics_Corp_",
"https://s3.amazonaws.com/supplybetter-synpgs/Samuel_Pressure_Vessel_Group",
"https://s3.amazonaws.com/supplybetter-synpgs/Savelle_Precision",
"https://s3.amazonaws.com/supplybetter-synpgs/SCHOTT",
"https://s3.amazonaws.com/supplybetter-synpgs/Scicon_Technology",
"https://s3.amazonaws.com/supplybetter-synpgs/Seal_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/Seastrom_Manufacturing_Co_",
"https://s3.amazonaws.com/supplybetter-synpgs/Seattle_Powder_Coat",
"https://s3.amazonaws.com/supplybetter-synpgs/Seattle_Stainless_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Sel_Tech_International",
"https://s3.amazonaws.com/supplybetter-synpgs/SF_Shops_to_try",
"https://s3.amazonaws.com/supplybetter-synpgs/Shmaze_Custom_Coatings",
"https://s3.amazonaws.com/supplybetter-synpgs/Siverson_Design",
"https://s3.amazonaws.com/supplybetter-synpgs/Smalley",
"https://s3.amazonaws.com/supplybetter-synpgs/Solid_Concepts",
"https://s3.amazonaws.com/supplybetter-synpgs/SpectraChrome",
"https://s3.amazonaws.com/supplybetter-synpgs/Spectrum_Plastics_Group",
"https://s3.amazonaws.com/supplybetter-synpgs/SS_Optical_Company",
"https://s3.amazonaws.com/supplybetter-synpgs/Stellartech_Research_Corp_",
"https://s3.amazonaws.com/supplybetter-synpgs/Sun_Power_Technologies_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Sunset_Glass",
"https://s3.amazonaws.com/supplybetter-synpgs/Superior_Imprint_Inc",
"https://s3.amazonaws.com/supplybetter-synpgs/TAP_Plastics",
"https://s3.amazonaws.com/supplybetter-synpgs/Teamvantage",
"https://s3.amazonaws.com/supplybetter-synpgs/Tech_Etch_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Terrazign",
"https://s3.amazonaws.com/supplybetter-synpgs/Terrene_Engineering",
"https://s3.amazonaws.com/supplybetter-synpgs/test",
"https://s3.amazonaws.com/supplybetter-synpgs/Tharco",
"https://s3.amazonaws.com/supplybetter-synpgs/The_D_R_Templeman_Co_",
"https://s3.amazonaws.com/supplybetter-synpgs/The_empty_format_for_vendor_information_list",
"https://s3.amazonaws.com/supplybetter-synpgs/The_QC_Group_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Thin_Metal_Parts",
"https://s3.amazonaws.com/supplybetter-synpgs/TMF_Inc",
"https://s3.amazonaws.com/supplybetter-synpgs/TorqMaster_Intl_",
"https://s3.amazonaws.com/supplybetter-synpgs/TOSS",
"https://s3.amazonaws.com/supplybetter-synpgs/Touch_International_ME_Vendor_Page",
"https://s3.amazonaws.com/supplybetter-synpgs/Trlby",
"https://s3.amazonaws.com/supplybetter-synpgs/ttteeesssttt",
"https://s3.amazonaws.com/supplybetter-synpgs/Tung_Tai_Group",
"https://s3.amazonaws.com/supplybetter-synpgs/Tung_Tai_Hardware_MFG",
"https://s3.amazonaws.com/supplybetter-synpgs/United_Western_Enterprises_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/US_Micro_Screw",
"https://s3.amazonaws.com/supplybetter-synpgs/VacuCoat_Technologies",
"https://s3.amazonaws.com/supplybetter-synpgs/Vaga_Industries",
"https://s3.amazonaws.com/supplybetter-synpgs/Vector_industries",
"https://s3.amazonaws.com/supplybetter-synpgs/Vendor_Visits_in_SF",
"https://s3.amazonaws.com/supplybetter-synpgs/Vision_Plastics",
"https://s3.amazonaws.com/supplybetter-synpgs/Visual_CNC_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Westwood_Precision_Inc_",
"https://s3.amazonaws.com/supplybetter-synpgs/Wise_Welding",
"https://s3.amazonaws.com/supplybetter-synpgs/Wolfram_Manufacturing",
"https://s3.amazonaws.com/supplybetter-synpgs/Zeus_Industries",
    ]

    carrier = []

    urls.each do |url|
      begin
        page = Nokogiri::HTML(open(url))
        div_wiki_content = page.css('#content > div.wiki-content')
        div_wiki_content_headers = div_wiki_content.css("h2")
        warnings = []

        #who updated, when was last update
        update = page.css("li.page-metadata-modification-info").text.strip

        #bullet points under capabilities, to make into tags
        tags_from_capabilities = [] 
        capability_header = div_wiki_content_headers.select{|header| header.attributes["id"].value.include?("Capabilities")}.first
        capability_list = capability_header.next_element
        capability_list.css("li").each do |li|
          tags_from_capabilities << li.text.strip if li.text.present?
        end
        warnings << "No tags from capabilties" if tags_from_capabilities.empty? 
      
        #need to check for longform content
        synopsis_header = div_wiki_content_headers.select{|header| header.attributes["id"].value.include?("CompanySynopsis")}.first
        synopsis_text = synopsis_header.next_element.text.strip
        (synopsis_text.present? and synopsis_text != "&nbsp") ? synopsis = synopsis_text : synopsis = nil

        focus_header = div_wiki_content_headers.select{|header| header.attributes["id"].value.include?("CoreFocus")}.first
        focus_text = focus_header.next_element.text.strip
        (focus_text.present? and focus_text != "&nbsp") ? focus = focus_text : focus = nil

        history_header = div_wiki_content_headers.select{|header| header.attributes["id"].value.include?("HistoryInformation")}.first
        history_text = history_header.next_element.text.strip
        (history_text.present? and history_text != "&nbsp") ? history = history_text : history = nil

        #flag if no contact information, otherwise get it
        contact = {}
        contact_header = div_wiki_content_headers.select{|header| header.attributes["id"].value.include?("ContactInformation")}.first
        contact_paragraph = contact_header.next_element.text

        contact[:name] = contact_paragraph.scan(/Contact: (.*)/) if contact_paragraph.scan(/Contact: (.*)/).present?
        contact[:phone] = contact_paragraph.scan(/Phone: (.*)/) if contact_paragraph.scan(/Phone: (.*)/).present?
        contact[:fax] = contact_paragraph.scan(/Fax: (.*)/) if contact_paragraph.scan(/Fax: (.*)/).present?
        contact[:mobile] = contact_paragraph.scan(/Mobile: (.*)/) if contact_paragraph.scan(/Mobile: (.*)/).present?
        contact[:address] = contact_paragraph.scan(/Address: (.*)/) if contact_paragraph.scan(/Address: (.*)/).present?
        contact[:email] = contact_paragraph.scan(/E-mail: (.*)/) if contact_paragraph.scan(/E-mail: (.*)/).present?
        contact[:website] = contact_paragraph.scan(/Website: (.*)/) if contact_paragraph.scan(/Website: (.*)/).present?

        no_contact_info_flag = true
        contact.each do |key,value|
          if (value.empty? or !value[0][0].present?)
            contact[key] = nil
          else
            contact[key] = value[0][0].strip
            no_contact_info_flag = false
          end
        end
        warnings << "No contact information" if no_contact_info_flag

        #labels should become tags, warn if no labels
        label_links = page.css(".label-list > .label-container > .label")
        tags_from_labels = []
        label_links.each do |label_link|
          tags_from_labels << label_link.text.strip if label_link.text.present?
        end
        warnings << "No tags from labels" if tags_from_capabilities.empty? 

        carrier << {tags: tags_from_capabilities.concat(tags_from_labels), 
                warnings: warnings,
                contact: contact,
                url: url,
                update: update,
                longform: "Wiki history: #{history} Wiki focus: #{focus} Wiki synopsis: #{synopsis}"
              }
      rescue
        puts "error processing #{url}"
      end
    end

    return carrier 

  end

  def self.wiki_pages
    [["/display/Vendors/A-Brite+Plating", "A-Brite Plating"],
     ["/display/Vendors/Absolute+Manufacturing", "Absolute Manufacturing"],
     ["/display/Vendors/Acteron+Corp", "Acteron Corp"],
     ["/display/Vendors/Acu-Line+Corporation", "Acu-Line Corporation"],
     ["/display/Vendors/Adhesa+Plate", "Adhesa Plate"],
     ["/display/Vendors/Aetna+Plating", "Aetna Plating"],
     ["/display/Vendors/All+Flex+-+ME+Vendor+Page", "All Flex - ME Vendor Page"],
     ["/display/Vendors/Allied+Technologies", "Allied Technologies"],
     ["/display/Vendors/Alljack", "Alljack"],
     ["/pages/viewpage.action?pageId=23658946", "Argo Spring Manufacturing Co."],
     ["/pages/viewpage.action?pageId=23659591",
      "Artcraft Plating &amp; Finishing"],
     ["/pages/viewpage.action?pageId=23659311", "ASKO Processing Inc."],
     ["/display/Vendors/Astro+Electroplating", "Astro Electroplating"],
     ["/pages/viewpage.action?pageId=23658919", "Aurora Technologies Inc."],
     ["/display/Vendors/Automated+Metal+Technologies",
      "Automated Metal Technologies"],
     ["/display/Vendors/Blue+Streak", "Blue Streak"],
     ["/pages/viewpage.action?pageId=23659452", "Bob's Design Engineering Inc."],
     ["/display/Vendors/Buyken+Metal+Products", "Buyken Metal Products"],
     ["/pages/viewpage.action?pageId=23659428", "Capital Industries Inc."],
     ["/display/Vendors/Cascade+Container", "Cascade Container"],
     ["/display/Vendors/Cascade+Precision+Incorporated",
      "Cascade Precision Incorporated"],
     ["/display/Vendors/Cascade+Quality+Molding", "Cascade Quality Molding"],
     ["/display/Vendors/ChikaBird", "ChikaBird"],
     ["/display/Vendors/Cirexx+-+ME+Vendor+Page", "Cirexx - ME Vendor Page"],
     ["/display/Vendors/Ciscotec", "Ciscotec"],
     ["/display/Vendors/Classic+Components", "Classic Components"],
     ["/display/Vendors/Component+Surfaces", "Component Surfaces"],
     ["/display/Vendors/Composite+Applications", "Composite Applications"],
     ["/display/Vendors/Constance+Machine", "Constance Machine"],
     ["/display/Vendors/Cybershield", "Cybershield"],
     ["/display/Vendors/CyberTouch+-+ME+Vendor+Page",
      "CyberTouch - ME Vendor Page"],
     ["/pages/viewpage.action?pageId=23658810",
      "Definitive Solutions &amp; Technologies, Inc."],
     ["/display/Vendors/DOTT+Industries", "DOTT Industries"],
     ["/display/Vendors/Douglas+Corp", "Douglas Corp"],
     ["/pages/viewpage.action?pageId=23659603", "Duray Plating Co."],
     ["/display/Vendors/Dynacept", "Dynacept"],
     ["/display/Vendors/Emerald+city+graphics", "Emerald city graphics"],
     ["/display/Vendors/Epner+Technology", "Epner Technology"],
     ["/display/Vendors/Express+Finishing", "Express Finishing"],
     ["/display/Vendors/Farwest+Aircraft", "Farwest Aircraft"],
     ["/display/Vendors/Farwest+Fabrication", "Farwest Fabrication"],
     ["/display/Vendors/Finishing+Unlimited+Inc", "Finishing Unlimited Inc"],
     ["/display/Vendors/Form+Factor+Inc", "Form Factor Inc"],
     ["/display/Vendors/Fotofab", "Fotofab"],
     ["/display/Vendors/Frank+Ward+Precision+Prototype",
      "Frank Ward Precision Prototype"],
     ["/display/Vendors/Gardico+Incorporated", "Gardico Incorporated"],
     ["/display/Vendors/Gary+Hansen", "Gary Hansen"],
     ["/display/Vendors/General+Super+Plating", "General Super Plating"],
     ["/display/Vendors/Gillaspie+Manufacturing", "Gillaspie Manufacturing"],
     ["/display/Vendors/High+End+Finishes", "High End Finishes"],
     ["/pages/viewpage.action?pageId=23658651", "High Energy Metals Inc."],
     ["/pages/viewpage.action?pageId=23658802", "Industrial Service Co."],
     ["/display/Vendors/Innovation+Fabrication", "Innovation Fabrication"],
     ["/display/Vendors/Italix", "Italix"],
     ["/display/Vendors/JetEdge", "JetEdge"],
     ["/pages/viewpage.action?pageId=23659307", "Jimani Inc."],
     ["/pages/viewpage.action?pageId=23659601", "Kelly Plating Co."],
     ["/pages/viewpage.action?pageId=23658898", "Kemeera Inc."],
     ["/display/Vendors/Kingstec", "Kingstec"],
     ["/display/Vendors/Koller+Craft+Plastic+Products",
      "Koller Craft Plastic Products"],
     ["/pages/viewpage.action?pageId=23659515", "Lancaster Metals Science Co."],
     ["/pages/viewpage.action?pageId=23659488", "Laser Light Technologies Inc."],
     ["/display/Vendors/Leader+Plating", "Leader Plating"],
     ["/display/Vendors/LiveWire+Prototyping", "LiveWire Prototyping"],
     ["/display/Vendors/MC+Custom+Products", "MC Custom Products"],
     ["/display/Vendors/McKechnie+Vehicle+Components",
      "McKechnie Vehicle Components"],
     ["/display/Vendors/Metal+Motion", "Metal Motion"],
     ["/display/Vendors/Microform+Precision", "Microform Precision"],
     ["/display/Vendors/Model+Solution", "Model Solution"],
     ["/display/Vendors/Modelwerks", "Modelwerks"],
     ["/display/Vendors/Modern+Engineering", "Modern Engineering"],
     ["/pages/viewpage.action?pageId=23659089",
      "3D Systems, Inc. (formerly Moeller Design)"],
     ["/display/Vendors/Mold+Rite", "Mold Rite"],
     ["/display/Vendors/MPC+Plating", "MPC Plating"],
     ["/display/Vendors/NIC", "NIC"],
     ["/display/Vendors/Northwest+Etch+Technologies",
      "Northwest Etch Technologies"],
     ["/display/Vendors/Odyssey+Plastics", "Odyssey Plastics"],
     ["/display/Vendors/OmniFab", "OmniFab"],
     ["/display/Vendors/Omnitech", "Omnitech"],
     ["/display/Vendors/PacTec", "PacTec"],
     ["/display/Vendors/Pathway+design", "Pathway design"],
     ["/display/Vendors/Pathway+Designs", "Pathway Designs"],
     ["/display/Vendors/Pearce+Design+LLC", "Pearce Design LLC"],
     ["/display/Vendors/Pegasus+Northwest", "Pegasus Northwest"],
     ["/pages/viewpage.action?pageId=23659390", "Pequot Tool and Mfg. Inc."],
     ["/pages/viewpage.action?pageId=23658962", "Peridot Corp."],
     ["/display/Vendors/Pioneer+Metal+Finishing", "Pioneer Metal Finishing"],
     ["/display/Vendors/Plastic-Metal+Technologies", "Plastic-Metal Technologies"],
     ["/display/Vendors/Plastic+Platers+Inc", "Plastic Platers Inc"],
     ["/pages/viewpage.action?pageId=23659355", "Pro CNC Inc."],
     ["/display/Vendors/Production+Plating", "Production Plating"],
     ["/display/Vendors/Protocam", "Protocam"],
     ["/display/Vendors/Protomold", "Protomold"],
     ["/display/Vendors/Proto+Technologies", "Proto Technologies"],
     ["/pages/viewpage.action?pageId=23659000",
      "Prototek Sheetmetal Fabrication Inc."],
     ["/display/Vendors/Providence+Metallizing", "Providence Metallizing"],
     ["/pages/viewpage.action?pageId=23659492", "The QC Group, Inc."],
     ["/display/Vendors/Quaker+City+Plating", "Quaker City Plating"],
     ["/display/Vendors/Qualitel+Corp.+-+ME+Vendor+Page",
      "Qualitel Corp. - ME Vendor Page"],
     ["/display/Vendors/Queen+City+Plating", "Queen City Plating"],
     ["/pages/viewpage.action?pageId=23659545", "Quickparts Inc."],
     ["/display/Vendors/R.D.+Wing", "R.D. Wing"],
     ["/pages/viewpage.action?pageId=23658987", "Rapid Sheet Metal Inc."],
     ["/pages/viewpage.action?pageId=24052027", "Read Me (for Confluence 2.3)"],
     ["/display/Vendors/Reliance+Manufacturing+Corporation",
      "Reliance Manufacturing Corporation"],
     ["/display/Vendors/Ryerson", "Ryerson"],
     ["/display/Vendors/Scicon+Technology", "Scicon Technology"],
     ["/display/Vendors/Seal+Technologies", "Seal Technologies"],
     ["/pages/viewpage.action?pageId=23658985", "Seattle Stainless Inc."],
     ["/display/Vendors/Shmaze+Custom+Coatings", "Shmaze Custom Coatings"],
     ["/display/Vendors/Smalley", "Smalley"],
     ["/display/Vendors/Solid+Concepts", "Solid Concepts"],
     ["/display/Vendors/SpectraChrome", "SpectraChrome"],
     ["/display/Vendors/SS+Optical+Company", "SS Optical Company"],
     ["/display/Vendors/Sunset+Glass", "Sunset Glass"],
     ["/display/Vendors/Tech-Etch+-+ME+Vendor+Page", "Tech-Etch - ME Vendor Page"],
     ["/pages/viewpage.action?pageId=23659224",
      "Introduction of the Vendor Information (for Confluence 2.3)"],
     ["/display/Vendors/The+empty+format+for+vendor+information+list",
      "The empty format for vendor information list"],
     ["/display/Vendors/Terrene+Engineering", "Terrene Engineering"],
     ["/display/Vendors/Tharco", "Tharco"],
     ["/pages/viewpage.action?pageId=23658953", "The D.R. Templeman Co."],
     ["/display/Vendors/TMF++Inc", "TMF  Inc"],
     ["/display/Vendors/Touch+International+-+ME+Vendor+Page",
      "Touch International - ME Vendor Page"],
     ["/pages/viewpage.action?pageId=23659532",
      "United Western Enterprises, Inc."],
     ["/display/Vendors/VacuCoat+Technologies", "VacuCoat Technologies"],
     ["/display/Vendors/Vaga+Industries", "Vaga Industries"],
     ["/display/Vendors/Vector+industries", "Vector industries"],
     ["/display/Vendors/Vision+Plastics", "Vision Plastics"],
     ["/pages/viewpage.action?pageId=21725263", "Visual CNC Inc."],
     ["/pages/viewpage.action?pageId=23659386", "Westwood Precision Inc."],
     ["/display/Vendors/Wise+Welding", "Wise Welding"],
     ["/display/Vendors/Laser+Cutting+Northwest", "Laser Cutting Northwest"],
     ["/pages/viewpage.action?pageId=48103974", "Designcraft Inc."],
     ["/display/Vendors/General+Foundry+Service", "General Foundry Service"],
     ["/display/Vendors/FJM+Security+Products", "FJM Security Products"],
     ["/display/Vendors/BAI+China+-+ME+Vendor+Page", "BAI China - ME Vendor Page"],
     ["/display/Vendors/Sun+Power+Technologies+-+ME+Vendor+Page",
      "Sun Power Technologies - ME Vendor Page"],
     ["/display/Vendors/FULLRIVER+-+ME+Vendor+Page", "FULLRIVER - ME Vendor Page"],
     ["/display/Vendors/Future+Power+Technologies+-+ME+Vendor+Page",
      "Future Power Technologies - ME Vendor Page"],
     ["/display/Vendors/Li-Polymer+Batteries+-+ME+Vendor+Page",
      "Li-Polymer Batteries - ME Vendor Page"],
     ["/display/Vendors/BYD+-+ME+Vendor+Page", "BYD - ME Vendor Page"],
     ["/display/Vendors/GMBattery+-+ME+Vendor+Page", "GMBattery - ME Vendor Page"],
     ["/display/Vendors/Goldstar+Mold+-+Shenzhen", "Goldstar Mold - Shenzhen"],
     ["/display/Vendors/US+Micro+Screw", "US Micro Screw"],
     ["/display/Vendors/Nebula+Design", "Nebula Design"],
     ["/pages/viewpage.action?pageId=51085835", "TorqMaster Intl."],
     ["/pages/viewpage.action?pageId=51086027", "Stellartech Research Corp."],
     ["/display/Vendors/Duke+Empirical", "Duke Empirical"],
     ["/display/Vendors/Accellent", "Accellent"],
     ["/pages/viewpage.action?pageId=51086036", "Pulse Technologies, Inc."],
     ["/display/Vendors/Creganna-Tactx+Medical", "Creganna-Tactx Medical"],
     ["/display/Vendors/Proven+Process+Medical+Devices",
      "Proven Process Medical Devices"],
     ["/display/Vendors/Flock-Tex", "Flock-Tex"],
     ["/display/Vendors/Acrylic+Concepts", "Acrylic Concepts"],
     ["/display/Vendors/Jemco", "Jemco"],
     ["/pages/viewpage.action?pageId=54558817",
      "Moeller Design &amp; Development"],
     ["/display/Vendors/PacWest+Sales", "PacWest Sales"],
     ["/display/Vendors/AmTouch+-+ME+Vendor+Page", "AmTouch - ME Vendor Page"],
     ["/pages/viewpage.action?pageId=56820074", "Pad Printing Services Inc."],
     ["/display/Vendors/Cole+ScreenPrint+Inc", "Cole ScreenPrint Inc"],
     ["/display/Vendors/Industrial+Plating+Corporation",
      "Industrial Plating Corporation"],
     ["/display/Vendors/Superior+Imprint+Inc", "Superior Imprint Inc"],
     ["/display/Vendors/GM+Nameplate", "GM Nameplate"],
     ["/display/Vendors/GKS+Services+Corp", "GKS Services Corp"],
     ["/display/Vendors/Fast+Signs", "Fast Signs"],
     ["/display/Vendors/Arcana+Precision+Machine", "Arcana Precision Machine"],
     ["/pages/viewpage.action?pageId=57508034", "Ferro-Ceramic Grinding, Inc."],
     ["/pages/viewpage.action?pageId=57508050", "INTA Technologies, Inc."],
     ["/display/Vendors/CoorsTek", "CoorsTek"],
     ["/display/Vendors/National+Instruments", "National Instruments"],
     ["/display/Vendors/Mikros+Engineering", "Mikros Engineering"],
     ["/display/Vendors/Read+Me", "Read Me"],
     ["/display/Vendors/ttteeesssttt", "ttteeesssttt"],
     ["/display/Vendors/test", "test"],
     ["/display/Vendors/Danco", "Danco"],
     ["/display/Vendors/RIM+Manufacturing", "RIM Manufacturing"],
     ["/display/Vendors/Rimstar", "Rimstar"],
     ["/display/Vendors/AIMMco", "AIMMco"],
     ["/display/Vendors/Spectrum+Plastics+Group", "Spectrum Plastics Group"],
     ["/display/Vendors/Vendor+Visits+in+SF", "Vendor Visits in SF"],
     ["/pages/viewpage.action?pageId=61279737", "Eika Kasei (HK) Co., Ltd."],
     ["/display/Vendors/Seattle+Powder+Coat", "Seattle Powder Coat"],
     ["/display/Vendors/Exotic+Tool+Welding", "Exotic Tool Welding"],
     ["/display/Vendors/Caliber+Precision", "Caliber Precision"],
     ["/display/Vendors/INCS", "INCS"],
     ["/display/Vendors/3M", "3M"],
     ["/pages/viewpage.action?pageId=62062878", "Master Spring &amp; Wire Form"],
     ["/pages/viewpage.action?pageId=62062920",
      "Advanced Prototype Technologies, Inc."],
     ["/display/Vendors/ABC+Imaging", "ABC Imaging"],
     ["/pages/viewpage.action?pageId=62914604", "Apex Industries, Inc."],
     ["/pages/viewpage.action?pageId=62915081",
      "RPDG (Rapid Product Development Group, Inc.)"],
     ["/display/Vendors/RK+Technologies", "RK Technologies"],
     ["/display/Vendors/Leader+Tech", "Leader Tech"],
     ["/pages/viewpage.action?pageId=63733894",
      "Cascade Engineering Services Inc."],
     ["/display/Vendors/Cascade+Engineering+Technologies",
      "Cascade Engineering Technologies"],
     ["/display/Vendors/Conrad+Manufacturing", "Conrad Manufacturing"],
     ["/pages/viewpage.action?pageId=63734353",
      "Saint-Gobain Performance Plastics Corp."],
     ["/display/Vendors/Double+D+Mfg", "Double D Mfg"],
     ["/display/Vendors/Mobius+Rapid+Prototyping", "Mobius Rapid Prototyping"],
     ["/display/Vendors/Henkel+Loctite", "Henkel Loctite"],
     ["/display/Vendors/RMC+Powder+Coating", "RMC Powder Coating"],
     ["/display/Vendors/Zeus+Industries", "Zeus Industries"],
     ["/display/Vendors/Jet+City+Laser", "Jet City Laser"],
     ["/display/Vendors/Wolfram+Manufacturing", "Wolfram Manufacturing"],
     ["/display/Vendors/Material+Connexion", "Material Connexion"],
     ["/display/Vendors/PTA+Plastics", "PTA Plastics"],
     ["/display/Vendors/Mary%27s+learning+Wiki", "Mary's learning Wiki"],
     ["/pages/viewpage.action?pageId=66816058", "First Cut (ProtoLabs)"],
     ["/display/Vendors/Motion+Mechanisms", "Motion Mechanisms"],
     ["/display/Vendors/O-Rings+West", "O-Rings West"],
     ["/display/Vendors/Apple+Rubber", "Apple Rubber"],
     ["/display/Vendors/Global+Lighting+Technologies",
      "Global Lighting Technologies"],
     ["/display/Vendors/GPI+Prototype+and+Manufacturing+Services",
      "GPI Prototype and Manufacturing Services"],
     ["/display/Vendors/Plastic+Innovations", "Plastic Innovations"],
     ["/display/Vendors/Sel-Tech+International", "Sel-Tech International"],
     ["/display/Vendors/Advanced+Molding+Technologies",
      "Advanced Molding Technologies"],
     ["/display/Vendors/ProtoCafe", "ProtoCafe"],
     ["/display/Vendors/Teamvantage", "Teamvantage"],
     ["/display/Vendors/MGS+Manufacturing+Group", "MGS Manufacturing Group"],
     ["/display/Vendors/Kaso+Plastics", "Kaso Plastics"],
     ["/display/Vendors/ARRK", "ARRK"],
     ["/display/Vendors/Douglas+Stamping", "Douglas Stamping"],
     ["/display/Vendors/Dynacast", "Dynacast"],
     ["/display/Vendors/SCHOTT", "SCHOTT"],
     ["/display/Vendors/EuroKera", "EuroKera"],
     ["/display/Vendors/Trlby", "Trlby"],
     ["/display/Vendors/TOSS", "TOSS"],
     ["/display/Vendors/Leister", "Leister"],
     ["/display/Vendors/LPKF", "LPKF"],
     ["/pages/viewpage.action?pageId=74811353", "Plastic Assembly Systems (PAS)"],
     ["/display/Vendors/Rayotek", "Rayotek"],
     ["/display/Vendors/Abrisa+Technologies", "Abrisa Technologies"],
     ["/pages/viewpage.action?pageId=75465402", "Faspro Inc."],
     ["/pages/viewpage.action?pageId=75465881", "Ferrera Tooling Inc."],
     ["/display/Vendors/Potential+ME+Vendors+List", "Potential ME Vendors List"],
     ["/display/Vendors/Ideas+Prototyped+LLC", "Ideas Prototyped LLC"],
     ["/display/Vendors/Reell+Precision+Manufacturing",
      "Reell Precision Manufacturing"],
     ["/display/Vendors/Lee+Spring", "Lee Spring"],
     ["/display/Vendors/Alternative+Molding+Concepts",
      "Alternative Molding Concepts"],
     ["/display/Vendors/Laser+Reproductions", "Laser Reproductions"],
     ["/display/Vendors/Herold+Precision+Metals", "Herold Precision Metals"],
     ["/display/Vendors/Genesis+Plastics+Welding", "Genesis Plastics Welding"],
     ["/display/Vendors/Kinetics", "Kinetics"],
     ["/display/Vendors/Pinehurst", "Pinehurst"],
     ["/display/Vendors/Terrazign", "Terrazign"],
     ["/display/Vendors/CymMetrick", "CymMetrick"],
     ["/display/Vendors/Northern+Engraving", "Northern Engraving"],
     ["/display/Vendors/Micro+Machine+Shop", "Micro Machine Shop"],
     ["/display/Vendors/SF+Shops+to+try", "SF Shops to try"],
     ["/display/Vendors/Cardinal+Paint", "Cardinal Paint"],
     ["/display/Vendors/DYMAX", "DYMAX"],
     ["/display/Vendors/Ellsworth", "Ellsworth"],
     ["/display/Vendors/Sabic+Innovative+Plastics", "Sabic Innovative Plastics"],
     ["/pages/viewpage.action?pageId=81232404",
      "Arlington Plating Company / Select Connect Technologies"],
     ["/display/Vendors/Bayer+MaterialScience", "Bayer MaterialScience"],
     ["/display/Vendors/TAP+Plastics", "TAP Plastics"],
     ["/display/Vendors/RTP+Plastics+Company", "RTP Plastics Company"],
     ["/pages/viewpage.action?pageId=81233030",
      "Mitsubishi Engineered Plastics (MEP)"],
     ["/display/Vendors/Lubrizol+Advanced+Materials",
      "Lubrizol Advanced Materials"],
     ["/display/Vendors/PolyOne", "PolyOne"],
     ["/pages/viewpage.action?pageId=81233116", "LensOne/Lens Technology"],
     ["/display/Vendors/Corning+Glass", "Corning Glass"],
     ["/pages/viewpage.action?pageId=81233147", "Custom Mold &amp; Design"],
     ["/display/Vendors/Cymmetrik", "Cymmetrik"],
     ["/display/Vendors/Harting+MID", "Harting MID"],
     ["/display/Vendors/Nissha+USA", "Nissha USA"],
     ["/display/Vendors/Fathom", "Fathom"],
     ["/pages/viewpage.action?pageId=81888724", "Molex Antenna/MID Division"],
     ["/display/Vendors/Micron+3D+Printing", "Micron 3D Printing"],
     ["/display/Vendors/Fluke+Metal+Products", "Fluke Metal Products"],
     ["/display/Vendors/Thin+Metal+Parts", "Thin Metal Parts"],
     ["/display/Vendors/Component+Supply+Company", "Component Supply Company"],
     ["/display/Vendors/HN+Lockwood", "HN Lockwood"],
     ["/display/Vendors/Control+Plastics", "Control Plastics"],
     ["/display/Vendors/Asahi+Group", "Asahi Group"],
     ["/display/Vendors/Feedback+on+Coxon", "Feedback on Coxon"],
     ["/display/Vendors/Coxon", "Coxon"],
     ["/display/Vendors/Tung+Tai+Group", "Tung Tai Group"],
     ["/pages/viewpage.action?pageId=84083378",
      "American Precision Protoyping (APP)"],
     ["/display/Vendors/Oakdale+Precision", "Oakdale Precision"],
     ["/display/Vendors/image", "image"],
     ["/display/Vendors/Alliance+Packaging", "Alliance Packaging"],
     ["/display/Vendors/Allpak+Container", "Allpak Container"],
     ["/display/Vendors/ASH+Industries", "ASH Industries"],
     ["/display/Vendors/Reliance+Engineering", "Reliance Engineering"],
     ["/display/Vendors/Protolabs", "Protolabs"],
     ["/display/Vendors/Tung+Tai+Hardware+MFG", "Tung Tai Hardware MFG"],
     ["/display/Vendors/Foctek+Photonics%2C+Inc", "Foctek Photonics, Inc"],
     ["/display/Vendors/JM+Victor", "JM Victor"],
     ["/display/Vendors/Cofan+USA", "Cofan USA"],
     ["/display/Vendors/Accuratus+Corporation", "Accuratus Corporation"],
     ["/display/Vendors/ACM+Holding", "ACM Holding"],
     ["/pages/viewpage.action?pageId=24608901",
      "All West Components &amp; Fasteners Inc."],
     ["/display/Vendors/Altaflex+-+ME+Vendor+Page", "Altaflex - ME Vendor Page"],
     ["/display/Vendors/Cashmere+Molding", "Cashmere Molding"],
     ["/display/Vendors/Chicago+White+Metal+Casting",
      "Chicago White Metal Casting"],
     ["/display/Vendors/Concept+Reality", "Concept Reality"],
     ["/display/Vendors/E-Fab", "E-Fab"],
     ["/display/Vendors/Engent+-+ME+Vendor+Page", "Engent - ME Vendor Page"],
     ["/display/Vendors/Fastenix", "Fastenix"],
     ["/display/Vendors/Gumstix+-+ME+Vendor+Page", "Gumstix - ME Vendor Page"],
     ["/display/Vendors/Made+3D", "Made 3D"],
     ["/display/Vendors/Magic+Metals", "Magic Metals"],
     ["/pages/viewpage.action?pageId=24608869", "McSweeney Steel Co."],
     ["/display/Vendors/Midwest+Prototyping", "Midwest Prototyping"],
     ["/pages/viewpage.action?pageId=33718321",
      "RPDG (Rapid Product Development Group)"],
     ["/display/Vendors/Samuel+Pressure+Vessel+Group",
      "Samuel Pressure Vessel Group"],
     ["/display/Vendors/Savelle+Precision", "Savelle Precision"],
     ["/pages/viewpage.action?pageId=24052149", "Seastrom Manufacturing Co."],
     ["/display/Vendors/Siverson+Design", "Siverson Design"]
   ]
  end

end